#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# See the output of "$0 -h" for details.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

for appro_old in target/okh_v1/orig/www_appropedia_org____okh_php_title_*.yml
do
	appro_new="$(printf '%s' "$appro_old" | sed -e 's/____okh_php_/____generateOpenKnowHowManifest_php_/')"
	if [ -f "$appro_new" ]
	then
		rm "$appro_old"
	else
		mv "$appro_old" "$appro_new"
	fi
done

